travis:
  secure:
    BINSTAR_TOKEN: p0DOkBzv8IfFZac8DXDuD0z74tuW8ZwFJSmkV/Yx88EDetxdnKoA8ajs6sXaAcumJGExFHp1ay/RT/2HPU6PDOCcKYqPMnW2iO6uE1dFA1mlpMmyDVgyFSfv+5MbD6dKR/A2P3Zphsa03FbAmTAmNbTLxT9FyRKhirej4j5pORZ+ZszqCJQhojPpeuEUTkMoeqOVUjF2l3CRDFG+ZDX4csymAabsenGiO1ZIoO6av3HUs5gsiOCmUoNCk5ZZS87+UWQ0f3+OZPZBTsoXveNsBOXsRMxGep5RLBB+8u73FxOjvVeUX+WZPZxNT+EDqPS45iwRpmpznueMY9hsyzAf7hUDUjBjtv6xSxfqsiFlfAn8Q1OZ6xa+58v+9rselpTcuT1i4Dy3j0GGIOJw/Pz3/+UORNuur4w5NtIYu/ntWhWn0m4k+EkzVKFvHZnnqzsPb4EbnNqIftGiQKmjDKl8JaL76yuxZMar47dGZyDdgZJtL8uEBZS0wvpY5jOmHn/Kz71K4+Un5vld4kGHevZoXsZfy1ZucXCLEPJvJ0oYStkLXiLNKEhZRN7nj51EE+AXZm5uT1FX1CTTMDjLdsnCdwSRovpAMG9vpqipZkXlzzHvP0LuC9lyg3G35+FeuJfTLakDJtVwxSjX0aPGu0kknDjuYuaJhhtN0pSoNAmRcOQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
