travis:
  secure:
    BINSTAR_TOKEN: SLo2+I9OowWJJcGLiOgWHIh0ZqEkB2IvJhSkLWJKQo3ZXRCWM906/uc+naHgZyLeWJ1sv8DA4BlDRWk8O9Lga3icJNaLtsFbsqiE0/9KBUlFlX8fH/xkluNYI1DA2jhiy90Pze2qmEPyh+LYgM6vkqxzoD7+bpyD1q1uEVfbFQ3f5ISon+IcyX0HEKlulX0XbIrk71h6TKoWe2AaZ0lEXWAibkUWe/L+oqNyVdXtH6LbSZvN7USbQ13jEePloihnHGkYPz6aGrW98Wy6R9lXLCTOSfJr/6KPrfJNR+NR2GpFRd96AKpJhhQDurjppDgodxX+gllF0HYr8BLqG3MUEQbu6KN7gGOPpPbWGshDcUCBGE7PI772HWJimw7ZuF7m1tHYEm/121YKiYVAJSzbykW+8c86B+wbMZVxfVQ4RwdrbO0zHidOqGNTJF4X8IKM5W1AxgGpxSZ2giHAp75xrtrqn3EvjGmC0bteohNTGkBGEixDS3o3AciSRq6GBZI4y5kcf+L1GT/fHY3WYhe71V3J0/SRrdrC4bWudwVfzTFIaBMk9u5y3I6f4qwOnW9itVJ5nRAPAMWmc+jynk2jJicocqx4pGqSTBEBTyEycc9gghcpe0eHNiSpzN4pjXUVsGcKW5pRHmlWiOBYv8gVy1JuKxVPzjzbzG61YWPYLo4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
