travis:
  secure:
    BINSTAR_TOKEN: oYlWiHDkuY58LbL7e06VpAbKM3MciOb8PS72rs2J3+qzIEkHpyB1m7v0GTmU5YPaXQxH4m7hhobDxYS6Q0CVuPg9Ayjm3HA8wv2QnznbqUHPo6oAZDat+N7gpuGpnkhlugcs8LEUDcFMmZjY20N7TE20FK5F2FZ25lULOcsCVzOy8bcDfvAEqy8IeW75cQav8NxmnfzMy2fp2SbcLcM0PSqr6h0SFu6B4RTw8UMRHQDv3pSMim/UN8EprbYBzZtA0OGJvZOGsgy72eCePYODJHwdAz39rhUkI/irZ/x355uc5AGtjlfHYAnR8ttUuaYThsdolS1ULdct2nEZ8EV3VwpXUgNmefTakJ2dUyZ7Z6AUunOUTfRsBo5UTA7AxZyYfIWVQu/GU3eGUNfa2DAo5vPwTesi70czty4cbb18DWIScU4vA46KT98ipQa+DOkrj4g8XG4C525mBux9QNoTJ8mSl65HivuCGw+R93wERZJ4g1Tj5JE7t4DgQSMN3OxP1oDOzQBT/HPko5+oxT5Q+AJgNSku3dC6642Md/+HKgKN/sPkjMc+gARRMJ/GgoC/otX2jQkHKanB7NhO2vmYeWcVO9Q/Ex98WSxKuz8xamvGoxTgXfakvq/O2/IyEAS1+EoNpvbgYfEJHoebAXFhhB7XifwZG1LoNP+AHSPD+40=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
